# Generated by Django 5.0.2 on 2024-03-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagble',
            name='show',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
