# Generated by Django 5.0.2 on 2024-04-22 21:06

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagble',
            name='uuid_tag',
            field=models.CharField(max_length=17, unique=True, validators=[home.models.validate_mac_address]),
        ),
    ]
