# Generated by Django 5.0.2 on 2024-03-02 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_monitorado_tag_ble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorado',
            name='tag_ble',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tagble'),
        ),
    ]
