# Generated by Django 5.0.2 on 2024-04-22 21:12

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tagble_uuid_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry',
            name='uuid_rasp',
            field=models.CharField(max_length=17, unique=True, validators=[home.models.validate_mac_address]),
        ),
    ]
