# Generated by Django 5.0.2 on 2024-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pessoa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='mateus@gmail.com', max_length=80),
            preserve_default=False,
        ),
    ]
