# Generated by Django 5.0.2 on 2024-03-21 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_medicoespecialidade_especialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorado',
            name='local_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.local'),
        ),
    ]
