# Generated by Django 5.0.2 on 2024-04-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_local_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
