# Generated by Django 5.0.2 on 2024-04-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_monitorado_local_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
