# Generated by Django 5.0.2 on 2024-04-09 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_leituratag_monitorado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='salario',
        ),
        migrations.AlterField(
            model_name='leituratag',
            name='monitorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.monitorado'),
        ),
    ]
