# Generated by Django 5.0.2 on 2024-04-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_funcionario_data_admissao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='funcionario_ptr',
        ),
        migrations.RemoveField(
            model_name='recepcionista',
            name='funcionario_ptr',
        ),
        migrations.AlterField(
            model_name='acompanhante',
            name='paciente_acomp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.paciente'),
        ),
        migrations.AlterField(
            model_name='acompanhante',
            name='relacionamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitorado',
            name='local_atual',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.local'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='motivo_visita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='paciente_vis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.paciente'),
        ),
        migrations.DeleteModel(
            name='Enfermeiro',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Recepcionista',
        ),
    ]
