# Generated by Django 5.0.2 on 2024-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tagble_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagble',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
