# Generated by Django 5.0.2 on 2024-03-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tagble_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, default='mateus@gmail.com', max_length=80, null=True),
        ),
    ]
