# Generated by Django 5.0.2 on 2024-04-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_monitorado_local_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('medico', 'Médico'), ('enfermeiro', 'Enfermeiro'), ('administrativo', 'Administrativo'), ('limpeza', 'Limpeza')], default='enfermeiro', max_length=20),
            preserve_default=False,
        ),
    ]
