# Generated by Django 5.0.2 on 2024-04-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_funcionario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('acompanhante', 'Acompanhante'), ('visitante', 'Visitante'), ('funcionario', 'Funcionário')], default='paciente', max_length=20),
            preserve_default=False,
        ),
    ]
