# Generated by Django 5.0.2 on 2024-04-04 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_funcionario_tipo_pessoa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('enfermeiro', 'Enfermeiro'), ('acompanhante', 'Acompanhante'), ('visitante', 'Visitante'), ('objeto', 'Objeto')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='tipo',
        ),
        migrations.AddField(
            model_name='monitorado',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tipo'),
        ),
    ]
