# Generated by Django 5.0.2 on 2024-04-05 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_tipo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorado',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tipo'),
        ),
    ]
