# Generated by Django 5.0.2 on 2024-04-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_funcionario_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituratag',
            name='monitorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.monitorado'),
        ),
    ]
