# Generated by Django 5.0.2 on 2024-04-09 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_leituratag_monitorado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituratag',
            name='monitorado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.monitorado'),
        ),
    ]
